# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

paintings:
  url: /paintings
  param:
    module: default
    action: paintings

details:
  url: /paintings/get
  param:
    module: default
    action: details

bio:
  url: /bio
  param:
    module: default
    action: bio

contact:
  url: /contact
  param:
    module: default
    action: contact

# default rules
legacy_homepage:
  url:   /home
  param: { module: default, action: index }

homepage:
  url:   /
  param: { module: default, action: index }

